
# Managed by Hydra

defaults:
  - base

log:
  WandbLogger:
    project: HybridPC
    name: ${experiment_name}
  TensorBoardLogger:
    name: HybrdPC

trainer:
  max_epochs: 496

optimizer:
    _target_: torch.optim.Adam
    lr: 0.002

lr_decay:
  decay_start_epoch: 250

network:
  module: AutoDecoder

  positional_encoding: Fourier # Triplane
  latent_dim: 8
  seg_loss_weight: 0.2

  prepare_epochs: 2

  fourier_encoder:
    embedding_dim: 64

  seg_decoder:
    input_dim: 3
    hidden_dim: 64
    num_hidden_layers_before_skip: 2
    num_hidden_layers_after_skip: 2

  functa_decoder:
    input_dim: 3
    hidden_dim: 64
    num_hidden_layers_before_skip: 2
    num_hidden_layers_after_skip: 2
