
# Managed by Hydra

defaults:
  - base

log:
  WandbLogger:
    project: HybridPC
    name: ${experiment_name}
  TensorBoardLogger:
    name: HybrdPC

trainer:
  max_epochs: 496

optimizer:
    target_: torch.optim.Adam
    lr: 0.004
    inner_loop_steps: 10
    inner_loop_lr: 0.1

lr_decay:
  decay_start_epoch: 250

dense_generator:
  num_steps: 10
  threshold: 0.1


network:
  module: AutoDecoder

  m: 16 # 16 or 32 (U-Net hidden dimension)
  backbone_type: UNet # Conv or UNet
  blocks: [1, 2, 3, 2, 1]
  cluster_blocks: [1, 2, 3]
  block_reps: 2

  positional_encoding: Fourier # Triplane
  modulation_dim: 32
  latent_dim: 64 #
  seg_loss_weight: 0.5

  prepare_epochs: 2

  fourier_encoder:
    embedding_dim: 64

  seg_decoder:
    input_dim: 3
    hidden_dim: 64
    num_hidden_layers_before_skip: 2
    num_hidden_layers_after_skip: 2

  functa_decoder:
    input_dim: 3
    hidden_dim: 64
    num_hidden_layers_before_skip: 2
    num_hidden_layers_after_skip: 2
