
# Managed by Hydra

defaults:
  - base

log:
  WandbLogger:
    project: hybridpc
    name: ${model.model.experiment_name}
  TensorBoardLogger:
    name: hybridpc

trainer:
  max_epochs: 496

optimizer:
    lr: 0.00015

lr_decay:
  decay_start_epoch: 250
  decay_stop_epoch: 496

model:

  module: NOCS
  pretrained_module: NOCS
  experiment_name: run_1
  positional_encoding: Fourier # Triplane

  latent_dimention: 1024
  fourier_encoder:
    embedding_dim: 1024

  seg_decoder:
    input_dim: 3
    hidden_dim: 512
    num_hidden_layers_before_skip: 2
    num_hidden_layers_after_skip: 2

  functa_decoder:
    input_dim: 3
    hidden_dim: 512
    num_hidden_layers_before_skip: 2
    num_hidden_layers_after_skip: 2
