
# Managed by Hydra

defaults:
  - base

stage1_ckpt_path: None
# stage1_ckpt_path: 
stage2_ckpt_path: None
# log:
#   WandbLogger:
#   project: HybridPC
#   name: ${experiment_name}
#   TensorBoardLogger:
#     name: HybrdPC

trainer:
  max_epochs: 512

training_stage: 0

optimizer:
    target_: torch.optim.Adam
    lr: 0.002
    inner_loop_steps: 10
    inner_loop_lr: 0.001
    latent_lr: 0.001
    decreased_by: 10

lr_decay:
  decay_start_epoch: 350

dense_generator:
  num_steps: 10
  threshold: 0.1
  num_points: 900000
  filter_val: 0.009
  prepare_epochs: 450


network:
  module: MetaDecoder

  # m: 16 # 16 or 32 (U-Net hidden dimension)
  backbone_type: UNet # Conv or UNet
  blocks: [1, 2, 3]
  cluster_blocks: [1, 2]
  block_reps: 2
  seg_blocks: [1, 2, 3]
  functa_blocks: [1, 2, 3]
  seg_block_reps: 2
  functa_block_reps: 2

  use_color: True
  use_normal: False

  positional_encoding: Fourier # Triplane
  modulation_dim: 64
  latent_dim: 64 #
  seg_loss_weight: 0.5

  prepare_epochs: 100

  fourier_encoder:
    embedding_dim: 32

  seg_decoder:
    input_dim: 3
    hidden_dim: 64
    num_hidden_layers_before_skip: 2
    num_hidden_layers_after_skip: 2

  functa_decoder:
    input_dim: 3
    hidden_dim: 64
    num_hidden_layers_before_skip: 2
    num_hidden_layers_after_skip: 2
