
# Managed by Hydra

defaults:
  - base

stage1_ckpt_path: None
# stage1_ckpt_path: 
stage2_ckpt_path: None
# log:
#   WandbLogger:
#     project: HybridPC
#     name: ${experiment_name}
#   TensorBoardLogger:
#     name: HybrdPC

trainer:
  max_epochs: 512

optimizer:
    target_: torch.optim.Adam
    lr: 0.002
    inner_loop_steps: 3

lr_decay:
  decay_start_epoch: 350

training_stage: 0

network:
  module: VanillaMinkowski

  # m: 16 # 16 or 32 (U-Net hidden dimension)
  backbone_type: MinkUNet34C # Conv, UNet or MinkUNet34C

  use_color: True
  use_normal: False
  use_xyz: False
  feature_in: mixed_latent # random_latent, voxel_features or mixed_latent 
  use_decoder: True

  positional_encoding: Fourier # Triplane
  modulation_dim: 64
  latent_dim: 64 #

  prepare_epochs: 30

  fourier_encoder:
    embedding_dim: 32

  seg_decoder:
    input_dim: 3
    hidden_dim: 64
    num_hidden_layers_before_skip: 2
    num_hidden_layers_after_skip: 2