
# Managed by Hydra

defaults:
  - base

stage1_ckpt_path: None
# stage1_ckpt_path: 
stage2_ckpt_path: None

# ckpt_path: '/home/zhenli/projects/data/output/Scannet/AutoEncoder/Narval_checkpoints/VanillaMinkowski_Fixed-Unet-voxel-0.5_overfit-False_intake--1_use-decoder-True_neighbors-1-blocks-5_latent-64-64_lr-0.002_cc-narval_run_1_epoch=9.ckpt' 


# log:
#   WandbLogger:
#     project: HybridPC
#     name: ${experiment_name}
#   TensorBoardLogger:
#     name: HybrdPC

trainer:
  max_epochs: 512

optimizer:
    target_: torch.optim.Adam
    lr: 0.002
    inner_loop_steps: 3

lr_decay:
  decay_start_epoch: 350

training_stage: 3

network:
  module: VanillaMinkowski

  # m: 16 # 16 or 32 (U-Net hidden dimension)
  backbone_type: MinkUNet34C # Conv, UNet or MinkUNet34C

  use_color: True
  use_normal: False
  use_xyz: False
  feature_in: mixed_latent # random_latent, voxel_features or mixed_latent 
  use_decoder: False

  positional_encoding: Fourier # Triplane
  latent_dim: 64 #

  prepare_epochs: 0

  seg_decoder:
    decoder_type: Concatenate # ConvONet or CrossAttention or Concatenate
    interpolation_mode: inverse_distance # inverse_distance or max or trilinear
    local_coords: True
    normalize_encoding: True
    k_neighbors: 1 # 1 for no interpolation

    input_dim: 3
    feature_dim: 64
    hidden_dim: 64
    num_hidden_layers_before_skip: 5
    num_hidden_layers_after_skip: 1

inference:
  split: val
  type: voxel # voxel or multiple_voxels or voxel or scene
  evaluate: True
  save_predictions: True
  visualization: False
  show_visualizations: True
  visualize_given_voxels: False
  visualize_ids: [406, 405, 366, 365, 403, 402, 410, 363, 409, 362]