
# Managed by Hydra

defaults:
  - base

stage1_ckpt_path: None

trainer:
  max_epochs: 512

optimizer:
    target_: torch.optim.Adam
    lr: 0.001

lr_decay:
  decay_start_epoch: 250

training_stage: 0

network:
  module: VanillaMinkowski
  backbone_type: MinkUNet34C # Conv, UNet or MinkUNet34C

  use_color: True
  use_normal: False
  use_xyz: False
  features_in: mixed_latent # random_latent, voxel_features or mixed_latent 
  use_decoder: False

  positional_encoding: Fourier # Triplane
  latent_dim: 64 #
  feature_dim: 64

  prepare_epochs: 0

  seg_decoder:
    input_dim: 3
    hidden_dim: 64
    activation: ReLU # ReLU or LeakyReLU or Softplus or ShiftedSoftplus
    num_hidden_layers_before: 2
    num_hidden_layers_after: 2