name: pcs4esr
channels:
  - pyg
  - nvidia/label/cuda-11.8.0
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - cuda-toolkit
  - pytorch==2.0.0
  - pytorch-cuda=11.8
  - pytorch-lightning=1.9.4 
  - lightning-bolts
  - pip:
      - tqdm
      - scipy
      - open3d
      - wandb
      - hydra-core
      - opencv-python
      - h5py
      - arrgh
      - plyfile
      - imageio-ffmpeg
      - ninja
      - gin-config
      - torchviz
      - trimesh
      - thop
      - cython
      - imageio
      - scikit-image
      - einops
      - torch-scatter -f https://data.pyg.org/whl/torch-2.0.0+cu118.html
      - nksr -f https://nksr.huangjh.tech/whl/torch-2.0.0+cu118.html
      - git+https://github.com/facebookresearch/pytorch3d.git@stable
      - spconv-cu118
      - timm
      - flash-attn --no-build-isolation
  - setuptools
