# Managed by Hydra

hydra:
  output_subdir: null
  run:
    dir: .

defaults:
  - _self_
  - data: base
  - model: base

experiment_name: ${model.network.module}_overfit-${data.over_fitting}_intake-${data.take}_${data.voxel_size}_latent-${model.network.latent_dim}_inner-steps-${model.optimizer.inner_loop_steps}_lr-${model.optimizer.lr}_blocks-${model.network.blocks}_run_1
project_root_path: ${hydra:runtime.cwd}
exp_output_root_path: ${project_root_path}/../data/output/${data.dataset}/${model.network.module}/${experiment_name}

global_train_seed: 123
global_test_seed: 321