# Managed by Hydra

hydra:
  output_subdir: null
  run:
    dir: .

defaults:
  - _self_
  - data: base
  - model: base

experiment_name: batch-1_voxel-0.1_overfitting-1-scenes_latent-32-64_3-inner_visualization_debug
project_root_path: ${hydra:runtime.cwd}
exp_output_root_path: ${project_root_path}/../data/output/${data.dataset}/${model.network.module}/${experiment_name}

global_train_seed: 123
global_test_seed: 321